title: Matias Menares
description: Matías Menares Ing. Informático

url: https://github.com/matiasmenares
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Inicio
   url: /index.html
 - title: Articulos
   url: /articles
 - title: Acerca de
   url: /about
 - title: Contacto
   url: /contact

social:
   github: matiasmenares
   twitter: matiasmenares
   facebook: 0mts0
   email: matias.menares@apptec.cl

google_analytics: "UA-58263416-1"
